services:
  sewlesew-api:
    container_name: sewlesewAPI
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
      - '5555:5555'
    environment:
      - PORT=3333
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
    networks:
      - sewlesewNet
volumes:
  mysql_data:
networks:
  sewlesewNet:
