services:
  sewlesew-api:
    container_name: sewlesewAPI
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
      - '5555:5555'
    env_file:
      - .env
    environment:
      - PORT=3333
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
    depends_on:
      sewlesew-db:
        condition: service_healthy
    networks:
      - sewlesewNet

  sewlesew-db:
    container_name: sewlesewDB
    image: mysql:8
    restart: always
    ports:
      - '3307:3306' # Expose MySQL's port 3306 to the host machine's 3307
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - sewlesewNet
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -u sls_usr -p${MYSQL_PASSWORD}']
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
networks:
  sewlesewNet:
