-- AlterTable
ALTER TABLE `Donation` ADD COLUMN `cardLast4` VARCHAR(191) NULL,
    ADD COLUMN `cardType` VARCHAR(191) NULL,
    MODIFY `paymentStatus` ENUM('PENDING', 'VERIFIED', 'FAILED') NOT NULL DEFAULT 'PENDING';
