export enum Role {
  USER = 'USER',
  SUPERADMIN = 'SUPERADMIN',
  CALLCENTERAGENT = 'CALLCENTERAGENT',
  CAMPAIGNREVIEWER = 'CAMPAIGNREVIEWER',
}

export enum AdminRole {
  SUPERADMIN = 'SUPERADMIN',
  CALLCENTERAGENT = 'CALLCENTERAGENT',
  CAMPAIGNREVIEWER = 'CAMPAIGNREVIEWER',
}

export enum SubAdminRoles {
  CALLCENTERAGENT = 'CALLCENTERAGENT',
  CAMPAIGNREVIEWER = 'CAMPAIGNREVIEWER',
}
