export enum Role {
  USER = 'USER',
  SUPERADMIN = 'SUPERADMIN',
  CALLCENTERAGENT = 'CALLCENTERAGENT',
  CAMPAIGNREVIEWER = 'CAMPAIGNREVIEWER',
}
export enum RoleTypes {
  USER = 'USER',
  ADMIN = 'ADMIN',
}
export enum AdminRole {
  SUPERADMIN = 'SUPERADMIN',
  CALLCENTERAGENT = 'CALLCENTERAGENT',
  CAMPAIGNREVIEWER = 'CAMPAIGNREVIEWER',
}

export enum SubAdminRoles {
  CALLCENTERAGENT = 'CALLCENTERAGENT',
  CAMPAIGNREVIEWER = 'CAMPAIGNREVIEWER',
}

export enum BusinessCategories {
  STARTUP_FUNDING = 'STARTUP_FUNDING',
  PRODUCT_LAUNCH = 'PRODUCT_LAUNCH',
  BUSINESS_EXPANSION = 'BUSINESS_EXPANSION',
  EVENT_SPONSORSHIP = 'EVENT_SPONSORSHIP',
  RESEARCH_AND_DEVELOPMENT = 'RESEARCH_AND_DEVELOPMENT',
  EQUIMEPNT_PURCHASE = 'EQUIPMENT_PURCHASE',
  MARKETING_AND_ADVERTISING = 'MARKETING_AND_ADVERTISING',
  WORKFORCE_TRAINING = 'WORKFORCE_TRAINING',
}

export enum CharityCategories {
  DISASTER_RELIEF = 'DISASTER_RELIEF',
  POVERTY_ALLEVIATION = 'POVERTY_ALLEVIATION',
  EDUCATION_SUPPORT = 'EDUCATION_SUPPORT',
  HEALTHCARE_ASSISTANCE = 'HEALTHCARE_ASSISTANCE',
  ELDERLY_ASSISTANCE = 'ELDERLY_ASSISTANCE',
  ENVIRONMENTAL_CONSERVATION = 'ENVIRONMENTAL_CONSERVATION',
  HUMAN_RIGHTS = 'HUMAN_RIGHTS',
  REFUGEE_AID = 'REFUGEE_AID',
}

export enum PersonalCharityCategoreis {
  MEDICAL = 'MEDICAL',
  RELOCATION = 'RELOCATION',
  REHABILITATION = 'REHABILITATION',
  DISASTER_RELIEF = 'DISASTER_RELIEF',
  LEGAL = 'LEGAL',
  CHILDCARE = 'CHILDCARE',
  EDUCATION = 'EDUCATION',
}
